### ISSUE TITLE
Update template for specifying extraArgs

### ISSUE THREAD

**Issue by verbotenj** [schemahero/schemahero-helm#11]
Currently, extraArgs has to be specified in a 'nonstandard' way otherwise we get an error

```
helm template .
Error: YAML parse error on schemahero/templates/manager.yaml: error converting YAML to JSON: yaml: line 37: could not find expected ':'
```
currently:
extraArgs: ['- --log-level', '- debug']

expected:
extraArgs: ['--log-level', 'debug']

**Comment by kworkbee** [comment]
https://github.com/schemahero/schemahero/blob/2e24a481338c3795abb9c0fdc20d27c86ef4606d/pkg/cli/managercli/run.go#L124-L128

There is no flag definition for log level, so it is not expected to be executed. It seems that the corresponding code needs to be modified.

In fact, even if extraArgs is specified, the following Pod logs are checked:

```
unknown flag: --enable-database-controller --log-level debug
```

**Comment by kworkbee** [comment]
https://github.com/schemahero/schemahero-helm/pull/12
